---
author: 'Keanu Rochette '
date: '`r format(Sys.Date())`'
title: MOBEAST chlorophyll concentration calculations
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

## Load the Libraries
```{r}
library(tidyverse) 
library(here)
library(gt) 
library(ghibli) 
```

## Load the Data
```{r}
chla <- read_csv(here("data", "chlorophyll_MOBEAST.csv"))
```

Volume filtered by cholorphyll should be around 125mL

If V1 < 120 mL, then calculate the rest
If V1, V2, V3 available : V1 + V2 + V3
If V1 and V3 available: [(V1x2 +V3) + (V1 + V3x3)] /2
If V2 and V3 available: [(V2x2 +V3) + (V2 + V3x3)] /2
If V3> 30: (V2+V3)/2 + V2+V3
```{r}




```




```{r}
chla %>% 
  mutate(conc_extractant = fluorometer*dilution_factor,
         filter_deposit = extraction_vol*conc_extractant/1000,
         chla_conc = round(filter_deposit/vol_filtered*1000, digits = 3))%>% 
  write_csv(here("outputs", "chla_conc.csv"))
```




