---
title: "MOBEAST - 24h Heatmap"
format: html
editor: source
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE)
```

## Load Libraries

```{r}
library(tidyverse)
library(lubridate)
library(here)
library(janitor)
library(ggrepel)
library(ghibli)
library(gt)
library(patchwork)
library(RColorBrewer)

library(ComplexHeatmap)
library(data.table)
library(dendextend)
library(grid)

# Rayna library
library(dendsort)
library(ggsci)
library(randomForest)
library(vegan)
library(ape)
library(devtools)
library(ggpubr)
library(viridis)
library(colorspace)
library(readr)
library(circlize)

```

Heatmap info and tutorial: https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html

## Functions

```{r}
source(here("scripts", "reference_scripts", "heatmap_zscore_function.R"))
```

## Data visualization theme

```{r}
nunu_theme <- theme_bw() + 
  theme(plot.title = element_text(size=14, face = "bold"), 
        plot.subtitle = element_text(size=12),
        axis.title = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size = 12, face = "bold"),
        legend.title=element_text(size=12, face = "bold"),
        legend.text=element_text(size=12),
        axis.text.x = element_text(angle= 45, hjust= 1),
        panel.background = element_rect(fill = "white"))
```

### Color palette

```{r}
treatment_colors = c(
  #Treatments
  "Control" = "grey",
  "Coral" = "#03A9F4",
  "CCA" = "#EF5350",
  "Algae" = "#4CAF50"
)

```

## Load Data

```{r}
meta <- read_csv(here("data", "MOBEAST_metadata_V2.csv"))
OTU_long <- read_csv(here("data","MOBEAST_DNA_long.csv"))

```

## Data Clean Up

```{r}
OTU_long <- OTU_long %>% clean_names() %>% select(-long_name, -tank_number, -treatment, -date,-time) %>%  rename(id_number= sample_id)

DNA <- meta %>% left_join(OTU_long)
```

### Preparing the OTU matrix for heatmap

```{r}
exclude_family <- DNA %>% group_by(family) %>% 
  filter(date == ymd("2024-06-02")| date == ymd("2024-06-03")) %>%
  reframe(sum = sum(abund)) %>% 
  filter(sum ==0) %>% 
  select(family) %>% 
  pull()
```

```{r}
OTU_htm_24h <- DNA %>% 
  filter(date == ymd("2024-06-02")| date == ymd("2024-06-03")) %>%
  filter(!family %in% exclude_family, 
         treatment !="Inflow") %>% 
  mutate(family_tax = paste(family, "X", order, "X", class, "X", phylum),
         genus_tax = paste(genus, "X", family, "X", order, "X", class, "X", phylum))
```




## Data with only the most abundant taxa 
```{r}
rare_taxa_threshold = 0.005
```

```{r}
# family
## per sample, min abundance "threshold" and more than 3x occurence. 
taxa_filtered <- OTU_htm_24h %>%
  group_by(id_number, family_tax) %>%
  mutate(sum_abund = sum(abund),
            time, treatment) %>% 
  ungroup() %>% 
  group_by(family_tax) %>%
  mutate(n_above_threshold = sum(sum_abund >= rare_taxa_threshold)) %>%
  filter(n_above_threshold >= 3) %>% 
  ungroup() %>% 
  mutate(taxa = family_tax)

taxa_filtered %>% select(taxa) %>% distinct()

```

```{}
# genus
## per sample, min abundance 0.5% and more than 3x occurence. 

taxa_filtered <- OTU_htm_24h %>%
  group_by(id_number, genus_tax) %>%
  mutate(sum_abund = sum(abund)) %>% 
  ungroup() %>% 
  group_by(genus_tax) %>%
  mutate(n_above_threshold = sum(sum_abund >= rare_taxa_threshold)) %>%
  filter(n_above_threshold >= 3) %>% 
  ungroup() %>% 
  mutate(taxa = genus_tax)
  
taxa_filtered %>% select(taxa) %>% distinct()
```

```{}
#family
## max abundance > threshold
taxa_filtered <- OTU_htm_24h %>%
  group_by(family_tax) %>%
  mutate(max = max(abund)) %>% 
  ungroup() %>% 
  filter(max >= rare_taxa_threshold) %>% 
  ungroup() %>% 
  mutate(taxa = family_tax)

taxa_filtered %>% select(taxa) %>% distinct()
```


```{}
# genus 
## max abundance > threshold

taxa_filtered <- OTU_htm_24h %>%
  group_by(genus_tax) %>%
  mutate(max = max(abund)) %>% 
  ungroup() %>% 
  filter(max >= rare_taxa_threshold) %>% 
  ungroup() %>% 
  mutate(taxa = genus_tax)

taxa_filtered %>% select(taxa) %>% distinct()
```


### SQRT-transformed Z-score 

```{r, echo=TRUE, collapse=TRUE}
#Make a heatmap of z-scored relative abundance data after it was summed by family
#https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html

# some the abundance of bacteria by family
family.culled.long.table <- taxa_filtered %>%
  group_by(id_number, taxa) %>%
  summarize(abund = sum(abund, na.rm = TRUE)) %>% 
  ungroup()

# Make wide format table to make a matrix later
family.culled.abund <- pivot_wider(family.culled.long.table, names_from = taxa, values_from = abund)

# Remove ID number from the data frame
## Z-score function only works on df that has a matrix format
culled.abund.OTU <- family.culled.abund %>% tibble() %>%  select(-id_number)

```

```{r}
sqrt.matrix <- apply(culled.abund.OTU, 2, FUN=sqrt)
sqrt.zscore <- as.data.frame(apply(sqrt.matrix, 2, FUN = zscore.calculation))
```

```{r}
# bring back the sample ID number in the df 
sqrt.zscore$id_number = family.culled.abund$id_number


# Set the ID numbers as the rownames (to make a matrix)
rownames(sqrt.zscore) = sqrt.zscore$id_number

# Remove the ID number column, convert the df to a matrix and transpose to make the final matrix.
sqrt.zscore.matrix <- sqrt.zscore %>% select(-id_number) %>% 
  as.matrix() %>% t()


```

### Heatmap

#### Annotation

```{r}
## Create a vector that will have information of a variable and its associate sample 
treatment <- meta[match(colnames(sqrt.zscore.matrix),
                           meta$id_number), 
                 "treatment"]

date_time <- meta[match(colnames(sqrt.zscore.matrix),
                           meta$id_number),
                  "date_time_string"]

time <- meta[match(colnames(sqrt.zscore.matrix),
                           meta$id_number),
                  "time_string"]

```


#### Organize the samples (ChatGPT)
```{r}

## organize the treatment in order they will be display on the heatmap
treatment2 <- factor(treatment$treatment, levels = c("Control", "Coral", "CCA", "Algae", "Inflow"))

## organize the time in order they will be display on the heatmap
time2 <- factor(time$time_string, levels = c("12:00:00", "18:00:00", "00:00:00", "06:00:00"))

#store that info in a df
col_info <- data.frame(
  Treatment = treatment2,
  Time = time2) %>% drop_na()

# create the order in which the samples with be organize in the heatmap
sample_order <- order(col_info$Treatment,col_info$Time)

# tell the matrix with my z-scores how the samples should be arranged
mat_ordered <- sqrt.zscore.matrix[, sample_order]

# have vectors specifying the order of the treatment for the heatmap
treatment_ordered <- col_info$Treatment[sample_order]
time_ordered <- col_info$Time[sample_order]


```

```{r}
## Create Annotation for the heatmap 
col_ha <- HeatmapAnnotation(
  #Treatment = treatment_ordered,
  
  ## Creates annotations blocks from treatments
  Treatment = anno_block(
    
  gp = gpar(fill = c("grey", "#03A9F4", "#EF5350", "#4CAF50")), # choose label colors
  #choose the name of the blocks
        labels = c("Control", "Coral", "CCA", "Algae"), 
  # customize the font color, size and font type
        labels_gp = gpar(col = "white", fontsize = 14,fontface = "bold")),
  
  # Creates clustering for time
  Time = time_ordered, 
  
  #Specifying the labels and the colors of the cluster groups.
  ## here Treatment is not very useful bcs they are specified above already
  col = list(Treatment = c("Control"="grey", 
                           "Coral"="#03A9F4", "CCA"="#EF5350",
                           "Algae"="#4CAF50"),
             Time = c("12:00:00" = "black",
                          "18:00:00" = "green", 
                          "00:00:00" = "blue",
                          "06:00:00" = "grey"))
)

```


#### Printing heatmap

```{r, fig.height = 16, fig.width = 24}
# Version 2
#png(width=1600, height=1000, file= here("outputs", "zscore_24hdata.png"))

ht = Heatmap(mat_ordered, 
             name = "sqrt z-scored", 
             heatmap_legend_param = list(legend_direction = "horizontal"),
             show_row_names = TRUE,
        row_names_max_width = unit(18, "cm"),
        clustering_method_rows = "complete",
        clustering_distance_rows = "euclidean",
             #rect_gp = gpar(col = "white", lwd = 0.1),
        
        column_title = "Bacterial Community Shift Over 24h", 
        column_title_gp = gpar(fontsize = 18, fontface = "bold"),
        #column_title_side = "bottom",
        cluster_rows = TRUE,
        cluster_columns =  FALSE,
        row_title = "Bacterial Families",
        row_title_gp = gpar(fontsize = 14, fontface = "bold"),
        row_names_gp = gpar(fontsize = 11),
        row_dend_width = unit(1.5, "cm"),
        #column_names_gp = gpar(fontsize = 10),
        show_column_names = FALSE,
        row_km = 3, # 5? number of forced segregation in rows 
        #column_km = 4,#number of forced segregation in columns 
        top_annotation = col_ha,
        #bottom_annotation = col_ha,
        column_split = treatment_ordered
        )
set.seed(1999)
ht_drawn <- draw(ht, heatmap_legend_side = "bottom",annotation_legend_side = "bottom", 
  merge_legends = TRUE)

#dev.off()

```

### Family Clusters and modules 

```{r}

# 4. Extract row positions grouped by cluster slice
cluster_list <- row_order(ht_drawn)

# 5. Convert the list into a clean, unified data frame matching gene names to cluster IDs
cluster_membership <- do.call(rbind, lapply(names(cluster_list), function(cl_name) {
  row_indices <- cluster_list[[cl_name]]
  data.frame(
    taxa = rownames(mat_ordered)[row_indices],
    cluster = paste("Cluster", cl_name)
  )
}))

cluster_membership
```


```{r}
modules <- taxa_filtered %>%  
  left_join(cluster_membership) 
  
```

```{}
modules <- modules %>%  
  mutate(cluster2 = cluster, 
         cluster = ifelse(cluster2 == "Cluster 1", "Oligotroph",
                          ifelse(cluster2 == "Cluster 2", "Copiotroph", "Generalist")),
         cluster = factor(cluster, levels = c("Generalist", "Oligotroph", "Copiotroph")))
```


## Plotting 

```{r}
modules_24h <- modules %>% 
  mutate(time_fac = factor(time, levels = c("12:00:00", "18:00:00", "00:00:00", "06:00:00")),
         treatment = factor(treatment, levels = c("Control", "Coral", "CCA", "Algae")))
```


```{r Family clustering, fig.width= 10, fig.height= 5}
modules_24h %>% drop_na(cluster) %>%
  group_by(id_number, cluster) %>% 
  reframe(sum_abund = sum(abund), time_fac, treatment) %>% 
  ungroup() %>% 
  group_by(treatment, time_fac, cluster) %>%
  reframe(mean_abund = mean(sum_abund),
          sd_abund   = sd(sum_abund),
          sum_abund) %>%
  ungroup() %>% 
  ggplot(aes(x = time_fac, y = mean_abund, group = treatment, color = treatment)) +
  geom_line() +
  geom_point()+
  geom_ribbon(aes(ymin = mean_abund - sd_abund,
                  ymax = mean_abund + sd_abund,
                  fill = treatment),
              alpha = 0.15, color = NA) +
  geom_point(aes(x = time_fac, y = sum_abund), shape = 1, alpha = 0.1) +
  labs(title = "Modules from Family Clustering", 
       x= "Time", 
       y= "Relative Abundance")+
  scale_color_manual(values = treatment_colors) +
  scale_fill_manual(values  = treatment_colors) +
  facet_wrap(. ~ cluster)+
  nunu_theme
```





