---
title: "MOBEAST_all_variables"
created: 5 Fev 2025
edited: 25 Fev 2025
format: html
editor: source

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE)
```

## Load Libraries

```{r}
library(tidyverse)
library(janitor)

library(here)

library(ggrepel)
library(ghibli)
library(gt)
library(patchwork)
library(RColorBrewer)
library(measurements)

library(car) # ANOVA package
library(ggeffects)
library(effects) #dependency for ggeffects
library(ggResidpanel) #residual panel
library(lme4)
library(lmerTest)
library(sjPlot)
library(emmeans)
library(performance)
library(multcompView)
library(broom.mixed)
```


## Data visualization theme

```{r}
nunu_theme <- theme_bw()+ 
  theme(plot.title = element_text(size=24, face = "bold"), 
        plot.subtitle = element_text(size=20),
        axis.title = element_text(size = 18, face = "bold"),
        axis.text = element_text(size = 16),
        strip.text.x = element_text(size = 16, face = "bold"),
        legend.title=element_text(size=18, face = "bold"),
        legend.text=element_text(size=16),
        strip.background = element_rect(fill = "white"))
```



```{r}
treatment_colors = c("Inflow"="#00838F",
                     "Control"="grey", 
                     "Coral"="#03A9F4", 
                     "CCA"="#EF5350", 
                     "Algae"="#4CAF50",
                     "Endmember" = "black", 
                     "Rain"= "yellow")
```

## Load Data

```{r}
mobeast <- read_csv(here("data", "MOBEAST_full_merged_data_long.csv"))
#mobeast <- read_csv(here("data", "MOBEAST_full_merged_data.csv"))
```


## Data Clean Up

### Outlier detection on bulk data
```{r}
## flagging outliers from the data set
 
mobeast_flagged <- mobeast %>%
  mutate(time_string = as.character(time_string),
              date_string = as.character(date_string),
              date_time_string = paste(date_string,time_string))%>% 
  #filter(treatment != "Endmember") 

  # flagging outliers
  ## grouping by treatment, variable 
  group_by(treatment, variable) %>% 
  ## get the mean and the sd to calculate mean +/- 2sd
  mutate(mean =mean(value, na.rm = T), 
         stand_dev = sd(value, na.rm = T)) %>% 
  ## Values outside of the mean +/- 2sd range are flagged as outliers
  ## Important to filter outliers later to understand why they are outliers. 
  mutate(outlier = ifelse(value > mean +2*stand_dev | value < mean -2*stand_dev,
                           "outlier", "not outlier")) %>% 
  ungroup() 
  

```



### Calculating Fluxes 
(([aquarium]-[inflow])*Vol) / (RT*SA ) in [umol/SA/time]. 
```{r}
tank_area = conv_unit(506.25, from = "cm2", to = "m2") # convert area cm2 to m2
tank_vol = 10 # liters
# DOC (npoc_u_m) in uM, i.e. umol/L
# flowrate in mL/s converted to L/sec
# residence_time in hours
# areal_flux in umol/s/m2
```

```{r}

mobeast_flux <- mobeast_flagged %>%  
  
  filter(treatment != "Rain") %>% 
  filter(treatment != "Endmember") %>% 
  
# Isolate inflow for each date_time and table
  group_by(date_time, inflow_table, variable) %>%
  mutate(inflow = value[treatment == "Inflow"]) %>%  
  ungroup() %>%
  
  # averaging the inflow values 
  group_by(date_time, variable) %>% 
  #mutate(inflow = ifelse(outlier == "outlier", inflow == NA, inflow)) %>% 
  mutate(inflow = mean(inflow, na.rm = TRUE)) %>%
  ungroup() %>% 
  
  # Normalize for treatments
  mutate(conc_norm = value - inflow)  %>%  
  relocate(inflow, .after = "conc_norm") %>% 
  relocate(date_time, .before = "date") %>%
  
  # convert res time from h to sec
  mutate(residence_time = residence_time*3600) %>%
  
  # There is no residence time in 
  mutate(residence_time = ifelse(date_time_string == "2024-06-04 12:00:00", (residence_time[date_time_string == "2024-06-02 12:00:00"] + residence_time[date_time_string == "2024-06-06 12:00:00"])*0.5, residence_time)) %>% 

  # Unsure why we still normalize to the inflow so calculated both 
  # fluxes with raw data and normalized data.
  mutate(areal_flux = conc_norm*tank_vol/ (residence_time*tank_area)) %>% 
  filter(treatment != "Inflow") %>% 
  
  #organize the treatment levels
  mutate(treatment = factor(treatment, levels = c("Control", "Coral", "CCA", "Algae", "Inflow"))) %>% 
  select(-mean, -stand_dev, -inflow)

```

```{r}
exclude_var <- c("carbonate", "residence time")
exclude_time <- c("03:00:00","09:00:00","15:00:00","21:00:00")
mobeast_flux <- mobeast_flux %>% filter(!variable_cat %in%  exclude_var,
                        !time_string %in% exclude_time) 
```


## 12PM data
```{r}
# removing outliers from the data set
mobeast_12PM <- mobeast_flux %>%
  filter(time_string == "12:00:00") %>% 
  
  ## remove the outliers 
  filter(outlier == "not outlier") 

```

```{}
mobeast_12PM %>%  select(id_number, tank_number, date_time_string, residence_time) %>% 
  distinct() %>% 
  ggplot(aes(x= date_time_string, y= residence_time, color = tank_number)) +
  geom_jitter()+
  stat_summary(color = "yellow", alpha =0.5)
```


## Iterative  coding 

```{r}
models_12PM <- mobeast_12PM %>%
  group_by(variable) %>%
  group_map(~ lmer(value ~ treatment + (1|tank_number), data = .x))
```


```{r}
# Loop Function:
## Take the 12PM samples and isolate the types of nutrient present on the df in a vector
## Create a list where the loop results will be save, named after the nutrients of the df
## In the for-loop, filter the df by nutrient and apply a statistical model with lmer
## Save the outputs of the model in the list such that each nutrient has its stats

mobeast_loop <- mobeast_12PM %>% select(variable) %>% distinct() %>% pull()

models_12PM <- vector(mode = "list", length = length(mobeast_loop))
names(models_12PM) <- mobeast_loop

#fit_12PM <- vector(mode = "list", length = length(mobeast_loop))
#names(fit_12PM) <- mobeast_loop

for (var in mobeast_loop) {
  df <- mobeast_12PM %>% filter(variable == var)
  models_12PM[[var]] <- lmer(areal_flux~ treatment + (1|tank_number), data = df)
  #fit_12PM[[var]] <- allFit(models_12PM[[var]])
}

```
```{r}
#fit_12PM

## Counted 61 instances where max and std dev not 0
```



```{r}

models <- mobeast_12PM %>%
  group_by(variable) %>%
  group_map(~ {
    mod <- lmer(areal_flux ~ treatment + (1|tank_number), data = .x)
    
    tibble(
      model = list(mod),
      singular = isSingular(mod),
      converged = is.null(mod@optinfo$conv$lme4$messages)
    )
  }) %>%
  bind_rows() %>% 
  filter(singular == TRUE | converged == FALSE)

models <- mobeast_12PM %>%group_by(variable) %>%
  group_modify(~ {
    mod <- lmer(areal_flux ~ treatment + (1|tank_number), data = .x)

    tibble(
      model = list(mod),
      singular = isSingular(mod),
      converged = is.null(mod@optinfo$conv$lme4$messages)
    )
  }) %>%
  ungroup() %>% filter(singular == TRUE)
```


```{r}
results <- imap_dfr(models_12PM, ~ tidy(.x) %>%
                     dplyr::mutate(variable = .y)) %>% 
  relocate(variable, .before = "effect")
```


```{r, warning= FALSE}
# So many Warnings! 
## Warning: The column names NumDF and DenDF in ANOVA output were not recognized or transformed.

anova_results <- imap_dfr(models_12PM, ~ {
  stats::anova(.x, type = 2) %>%
    broom::tidy() %>%
    mutate(variable = .y)}) %>%
  relocate(variable) %>% 
  filter(p.value <0.05)
```

```{r}
# "estimate" are negative somehow. Why? 
## in manual models for DOC, estimate >0, here it's <0
## t.ratio is "statistics", and negative instead of positive
## p.values not shown, only p.adjusted. 
emmeans_results <- imap_dfr(models_12PM, ~ {
  emmeans(.x, pairwise ~ treatment)$contrasts %>%
    broom::tidy() %>%
    mutate(variable = .y)}) %>% 
  relocate(variable) %>% 
  filter(contrast == "Control - Coral"| contrast == "Control - CCA"|contrast == "Control - Algae") 
```

```{r}
emmeans_results_sig <- emmeans_results %>% 
  filter(adj.p.value <0.05)
```


```{r}
emmean_sig <- emmeans_results_sig %>% pull(variable)
```

```{r, warning=FALSE}
mobeast_12PM %>% filter(variable %in% emmean_sig) %>% 
  ggplot(aes(x= treatment, y= areal_flux, fill = treatment))+
    geom_violin()+
    geom_jitter(aes(color = outlier), alpha = 0.5)+
    geom_hline(yintercept=0, linetype='dashed')+
    stat_summary(color = "yellow", alpha =0.5)+
    facet_wrap(~variable, scales = "free")+
    labs(title = paste("12PM Biogeochem Changes"),
       #subtitle = "Norm DOC = Tank DOC - Inflow DOC",
       x= "Treatment",
       y = "Flux XXX")+
  scale_fill_manual(breaks = c("Control", "Coral", "CCA", "Algae"), 
                       values=c("grey", "#03A9F4", "#EF5350", "#4CAF50"))+
  scale_color_manual(breaks = c("outlier", "not outlier"), 
                       values=c("red", "black"))+
    nunu_theme + 
    theme(axis.text = element_text(size = 18))
```


```{r}
DOC_12PM <- mobeast_12PM %>% filter(variable == "het_bact")
mod_12PM <- lmer(areal_flux~ treatment + (1|tank_number), data = DOC_12PM,
                 REML = FALSE, 
          control = lmerControl(optimizer ="Nelder_Mead"))
```

```{}
allFit(mod_12PM)
```


```{r}
summary(mod_12PM)
anova(mod_12PM, type = 2)
emmeans(mod_12PM, specs = trt.vs.ctrl ~ treatment)
#emmeans(models_12PM[[1]], ~ treatment)
```

```{r}
resid_panel(mod_12PM)

```


```{r}
 DOC_12PM %>%  
    ggplot(aes(x= treatment, y= areal_flux, fill = treatment))+
    geom_violin()+
    geom_jitter(aes(color = outlier), size = 2)+
    geom_hline(yintercept=0, linetype='dashed')+
    stat_summary(color = "yellow", alpha =0.5)+
    #coord_trans(y="log10")+
  #facet_wrap(~date_string, scales = "free")+
    labs(title = paste("12PM", "DOC", "Production"),
       x= "Treatment",
       y = "Areal Flux (µmol/s/m2)")+
  scale_fill_manual(breaks = c("Control", "Coral", "CCA", "Algae"), 
                       values=c("grey", "#03A9F4", "#EF5350", "#4CAF50"))+
  scale_color_manual(breaks = c("outlier", "not outlier"), 
                       values=c("red", "black"))+
  nunu_theme #+
  #theme(legend.position = "none")
```




## Hypothesis 2: There are variation in exudation on a diel cycle 24h

```{r}
## removing outliers from the data set
DOC_24h <- DOC_flux %>%
  filter(date_string == "2024-06-02"|date_string == "2024-06-03") %>% 
  filter(!is.na(id_number)) %>% 
  ## remove the outliers 
  filter(outlier == "not outlier") %>% 
  mutate(time_fac = factor(time_string, levels = c("12:00:00", "18:00:00",
                                                   "00:00:00","06:00:00"))) %>% 
  filter(time_string != "00:00:00") 
```

```{}
DOC_24h %>% filter(!is.na(id_number))
```

```{r}
mod <- lmer(areal_flux ~ treatment*time_fac + (1|tank_number), data = DOC_24h)
```

#### 24h Model setup and results
```{r}
summary(mod)
anova(mod, type = 2)
emmeans(mod, specs = trt.vs.ctrl ~ treatment)
#emmeans(models_24h[["DOC"]], ~ treatment)
```

```{r}
resid_panel(mod)
```


#### Data Visualization 
```{r}
DOC_24h %>% 
    ggplot(aes(x= treatment, y= areal_flux, fill = treatment))+
    geom_violin()+
    geom_jitter(aes(color = outlier), size = 2)+
    geom_hline(yintercept=0, linetype='dashed')+
    stat_summary(color = "yellow", alpha =0.5)+
    facet_wrap(~time_fac, ncol = 4 )+
    labs(title = paste("24h DOC Production"),
       #subtitle = "Norm DOC = Tank DOC - Inflow DOC",
       x= "Treatment",
       y = "Production (µmol/L)")+
  scale_fill_manual(breaks = c("Control", "Coral", "CCA", "Algae"), 
                       values=c("grey", "#03A9F4", "#EF5350", "#4CAF50"))+
  scale_color_manual(breaks = c("outlier", "not outlier"), 
                       values=c("red", "black"))+
    nunu_theme + 
    theme(axis.text = element_text(size = 18))#,
        #legend.position = "none") #+
  #geom_jitter(aes(color = inflow_table), size = 2)+
  #scale_color_manual(values = c("red", "blue"))+
  #theme(legend.position = "right")
```













