---
title: "MOBEAST DNA"
format: html
editor: visual
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE)
```

## Load Libraries
```{r}
library(tidyverse)
library(lubridate)
library(here)
library(janitor)
library(ggrepel)
library(ghibli)
library(gt)
library(patchwork)
library(RColorBrewer)

library(ComplexHeatmap)
library(data.table)

# Rayna library
library(dendsort)
library(ggsci)
library(randomForest)
library(vegan)
library(ape)
library(devtools)
library(ggpubr)
library(viridis)
library(colorspace)
library(readr)
library(circlize)

```

## Functions

### Heatmap Sean's function
```{r}
# Heat map funciton
# function to sum by family
prep_ht_mat = function(otus,
                       tax_table,
                       tax_level = "family",
                       cutoff = 40,
                       min_sam = 2,
                       scale_vals = F){
  if(tax_level == "OTU"){
    otu_sum = otus
    
  }else{
    otu_key = merge(otus,
                    tax_table[,
                              .SD,
                              .SDcols = c(tax_level, "OTU")], ## Make sure the seq are "ASV"
                    by = "OTU",
                    all.x = T)
    
    otu_key[, OTU := NULL]
    
    # sum by tax level
    otu_sum = otu_key[, lapply(.SD, sum), by = tax_level] #### maybe code crashes here
        ## Aggregates data by family
  }
  
  # order by most abundant taxa and subset to top N
  otu_sum[ , tax_sums := rowSums(otu_sum[ , .SD, .SDcols = !tax_level])]
  otu_sum = otu_sum[tax_sums > 0]
  otu_sum = otu_sum[order(tax_sums, decreasing = T)]
  otu_sum[ , tax_sums := NULL]
  otu_sum = otu_sum[1:cutoff,]
  
  # transform data.table to matrix
  otu_mat = as.matrix(otu_sum[, .SD,
                              .SDcols = !tax_level],
                      rownames.value = otu_sum[[tax_level]])
  
  # drop taxa that don't meet min sample count
  keep_tax = apply(otu_mat, 1, function(x)
    length(x[x > 0]) > min_sam)
  otu_mat = otu_mat[keep_tax, ]
  
  # optionally z-score a.k.a. scale values
  if (isTRUE(scale_vals)) {
    otu_mat = t(scale(t(otu_mat)))
  }
  
  return(otu_mat)
}
```

### Rayna's z-score function 

```{r, echo=FALSE, collapse=TRUE}

zscore.calculation = function(x) {
  #Inputs: x = dummy variable that function will be run on. Must be a vector of numbers.
  
  zscoredat=x #duplicate vector x, save as a new df zscoredat.
  
  for (i in 1:length(x)) { #for each value in vector x
    zscoredat[i]=(x[i]-mean(x))/sd(x) #subset the input data to the corresponding position, and make it equal to the zscored value of the original cell value at that position.
    #zscoring is done by subtracting the mean value for a vector from the value of the vector at position i, and then dividing by the SD for the vector.
  }
  zscoredat1 <<- zscoredat #save output as new df, zscoredat1
}

```

## Data visualization theme
```{r}
nunu_theme <- theme_bw() + 
  theme(plot.title = element_text(size=14, face = "bold"), 
        plot.subtitle = element_text(size=12),
        axis.title = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size = 12, face = "bold"),
        legend.title=element_text(size=12, face = "bold"),
        legend.text=element_text(size=12),
        axis.text.x = element_text(angle= 45, hjust= 1),
        panel.background = element_rect(fill = "azure1"))
```

### Color palette
```{r}
treatment_colors = c(
  #Treatments
  "Control" = "grey",
  "Coral" = "#03A9F4",
  "CCA" = "#EF5350",
  "Algae" = "#4CAF50"
)

```

## Creating metadata file
```{}
meta <- read_csv(here("data", "MOBEAST_metadata.csv"))
meta <-meta %>% clean_names()
table_id <- read_csv(here("data", "Laurel", "TableID.csv"))

table_id <- clean_names(table_id)

table_id <- table_id %>% rename(tank_number=tankid) %>% select(-treatment) %>% 
  mutate(tank_number = paste0("T", tank_number)) %>% 
  mutate(inflow_table = paste("Table", inflow_table))

inflow_id <- tibble(tank_number = c("F1", "F2"),
       inflow_table = c("Table 1", "Table 2"))
table_id <- rbind(table_id, inflow_id)

meta <- left_join(meta, table_id)

meta %>% relocate(inflow_table, .before = tank_number)

treat_code <- tibble(
  treatment = c("A", "K", "C", "R", "Inflow", "Endmember", "Rain"),
  full_name = c("Algae", "Coral", "Control", "CCA", "Inflow", "Endmember", "Rain")
)
treat_code

meta<- left_join(meta, treat_code)

meta <- meta %>% relocate(full_name, .before = treatment) %>% 
  select(-treatment) %>% 
  rename(treatment = full_name) %>% 
  filter(id_number != is.na(id_number),
         id_number == ifelse(str_detect(meta$id_number,"[ABC]"), id_number, "NA")) 
#write_csv(meta, here("data","MOBEAST_metadata_V2.csv"))
```

## Load Data 
```{r}
OTU <- read_csv(here("data", "DNA","MOBEAST_OTU_culled.csv"))
meta <- read_csv(here("data","MOBEAST_metadata_V2.csv"))
tax <- read_csv(here("data","DNA", "MOBEAST_tax_culled.csv"))
OTU_long <- read_csv(here("data","MOBEAST_DNA_long.csv"))

```


## Data clean-up

Reformating the date, time and date-time in the metadata file 
```{r, meta data clean up}
meta<- meta %>% mutate(time = str_pad(time, width = 4, side = "left", pad = "0"),
               time = str_replace(time, "(\\d{2})(\\d{2})", "\\1:\\2")) %>% 
  # "(\\d{2})(\\d{2})" separates the string in 2 groups of 2 characters
  # "\\1:\\2", group1 + ":" + group2
  mutate(time = paste0(time, ":00"),
               date_time = paste(date, time),
               date = mdy(date), 
               date_time = mdy_hms(date_time),
               time = factor(time))
  
  
```

Clean up the long format data to make it easier to merge with the meta data file
```{r}
OTU_long<- OTU_long %>% clean_names() %>% 
  mutate(id_number = sample_id) %>% 
  relocate(id_number, .before= otu_number) %>% 
  select(-sample_id, -date, -treatment, -time)
```

Fusion!
```{r}
OTU_htm <- left_join(OTU_long, meta)
```


## Z-Scored Heatmap
```{r, echo=TRUE, collapse=TRUE}
#Make a heatmap of z-scored relative abundance data after it was summed by family

#https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html

family.culled.long.table <- OTU_htm %>%
  group_by(id_number, family) %>%
  summarize(abund = sum(abund, na.rm = TRUE))

family.culled.abund <- pivot_wider(family.culled.long.table, names_from = family, values_from = abund)

```


```{r, nunu's}
#Remove sample ID from culled.abund.asv
culled.abund.OTU <- family.culled.abund %>% ungroup() %>% tibble() %>%  select(-id_number)

```


```{r, nunu's}
#zscore the data.subset1 dataset (i.e. no metadata)
#z.otu.subset = culled.abund.OTU.3[,c(2:92)]
z.zscore.data.otu.subset <- as.data.frame(apply(culled.abund.OTU, 2, FUN=zscore.calculation))
#Bring back Type.6 into df
z.zscore.data.otu.subset$id_number = family.culled.abund$id_number
```


```{r, nunu's}
#Make row names sample type, then remove group.1
rownames(z.zscore.data.otu.subset) = z.zscore.data.otu.subset$id_number

zscore.data.otu.matrix <- z.zscore.data.otu.subset %>% select(-id_number) %>% 
  as.matrix() %>% t()
```

```{r}
meta <- meta %>% mutate(treatment = as.character(treatment)) %>% 
  mutate(treatment = ifelse(id_number == "MOBEAST115", "Rain", 
                            ifelse(is.na(treatment), "Endmember", treatment))) %>% 
  mutate(inflow_table = ifelse(is.na(inflow_table), "Environmental data", inflow_table)) %>% 
  as.data.frame()
```

```{r}
treatment = meta[match(colnames(zscore.data.otu.matrix),
                           meta$id_number), 
                 "treatment"]

inflow_table = meta[match(colnames(zscore.data.otu.matrix),
                           meta$id_number),
                     "inflow_table"]


```

```{r}

ha = HeatmapAnnotation(
  treatment = treatment,
  inflow_table = inflow_table,
  col = list(treatment = c("Inflow"="#00838F","Control"="grey", "Coral"="#03A9F4", 
                           "CCA"="#EF5350", "Algae"="#4CAF50","Endmember" = "black", "Rain"= "yellow"),
             inflow_table = c("Table 1" = "yellow", "Table 2" = "orange", 
                              "Environmental data" = "blue"))
)


```

```{r, fig.height = 10, fig.width = 16}
ht = Heatmap(zscore.data.otu.matrix, name = "z-scored", rect_gp = gpar(col = "white", lwd = 0.1),
        column_title = "id_number", column_title_side = "bottom",
        row_title = "family",
        row_names_gp = gpar(fontsize = 10),
        column_names_gp = gpar(fontsize = 10),
        row_km = 10, #number of forced segregation in rows 
        column_km = 6,#number of forced segregation in columns 
        top_annotation = ha

        )

draw(ht)

#ggsave("MOBEAST_heatmap.png", width = 16, height = 10, path = here("outputs"))

```


















