---
title: "Linear regression to fix flow issue"
format: html
editor: source
---

# Libraries
```{r}
library(tidyverse)
library(janitor)
library(here)
library(ggforce)
library(ggh4x)
library(bestNormalize)
library(ggResidpanel)
library(broom)
library(ggrepel)
library(gt)
library(patchwork)
library(lme4)
#library(lmerTest)
```

#theme 

```{r}
nunu_theme <- theme_bw()+ 
  theme(plot.title = element_text(size=24, face = "bold"), 
        plot.subtitle = element_text(size=20),
        axis.title = element_text(size = 18, face = "bold"),
        axis.text = element_text(size = 16),
        strip.text.x = element_text(size = 16, face = "bold"),
        legend.title=element_text(size=18, face = "bold"),
        legend.text=element_text(size=16),
        strip.background = element_rect(fill = "white"))
```

# Data
```{r, message=FALSE}
mobeast <- read_csv(here("data", "mobeast_flux.csv"))
```

# Data clean up 
```{r}
mobeast<- mobeast %>% mutate(date_string = as.character(date_string), 
                   time_string = as.character(time_string), 
                   date_time_string= as.character(date_time_string))
mobeast %>% select(variable_cat, variable) %>% distinct()
```

```{r}
meta_label <- mobeast %>% select(variable_cat, variable) %>% distinct()
```



# Flux Linear regression 


```{r}
# test regression
DOC <- mobeast %>% filter(variable == "npoc_u_m") %>% filter(outlier != "outlier")

DOC_mod <- lm(asinh(areal_flux) ~ flowrate, data = DOC)
summary(DOC_mod)

resid_panel(DOC_mod)
anova(DOC_mod)

```


```{r}
mobeast %>% 
  #filter(variable == "npoc_u_m") %>% 
  ggplot(aes(sample = areal_flux)) +
  stat_qq() +
  stat_qq_line( color = "red") +
  facet_wrap(.~ variable, scales = "free")

```

```{r}
# automated model computation 
models <- mobeast %>%
  filter(outlier != "outlier") %>% 
  mutate(flowrate = log10(flowrate))%>% 
  group_by(variable) %>%
  nest() %>%
  mutate(
    model = map(data, ~ lm(areal_flux ~ flowrate, data = .x)),
    results = map(model, tidy),
    stats = map(model, glance)
  )
```



```{r}
lm_results <- models %>% unnest(results) %>% 
  select(variable, term, estimate, std.error, t_value = statistic, p.value)
lm_results %>% filter(p.value<0.05, term == "flowrate")
```

```{r}
# not all stats are saved in the DF
lm_stats <- models %>% unnest(stats) %>%  select(variable, r.squared, adj.r.squared,
                                     RSE = sigma, F_stat = statistic, p.value,  DF = df.residual)

lm_stats %>% filter(p.value <0.05)
```



```{r, warning = FALSE, fig.height=12, fig.width=20}
mobeast %>% 
  filter(outlier != "outlier") %>% 
  filter(variable_cat == "DOC"|variable_cat == "chla") %>% 
  #filter(variable =="pro"|variable =="syn"|variable =="pico_euk"|variable =="het_bact") %>% 
  ggplot(aes(x = flowrate, y = asinh(areal_flux), color = treatment)) +
  geom_point(size = 2, alpha = 0.8) +
  geom_point(shape = 21,color = "black", size = 2)+
  geom_smooth(method = "lm", se = TRUE, color = "red") +
  facet_wrap(~ variable, scales = "free_y", nrow= 2, ncol = 3) +
  theme_bw() +
  labs(
    x = "Flow rate",
    y = "Flux",
    title = "Flow rate vs Flux for each variable"
  )+
  scale_color_manual(
        breaks = c("Control", "Coral", "CCA", "Algae"),
        values = c("grey", "#03A9F4", "#EF5350", "#4CAF50")
      ) +
  nunu_theme
```

```{r, fig.height=50, fig.width=5}
mobeast %>% 
  filter(outlier != "outlier") %>% 
  mutate(flowrate = log10(flowrate)) %>% 
  ggplot( aes(x = flowrate, y = areal_flux)) +
  geom_point(size = 2, alpha = 0.8) +
  geom_smooth(method = "lm", se = TRUE, color = "blue") +
  
  facet_nested(
    variable_cat + variable~. ,
    scales = "free_y"
  ) +
  
  theme_bw(base_size = 14) +
  labs(
    x = "Flow rate",
    y = "Flux",
    title = "Flow rate vs Flux grouped by category"
  )
```



# Delta values Linear regression 

```{r}
mobeast_delta <- mobeast %>%
  filter(outlier != "outlier") %>% 
  mutate(date_string = as.character(date_string)) %>% 
  filter(date_string =="2024-06-02"|date_string =="2024-06-03") %>% 
  mutate(flowrate = log10(flowrate)) 


```

```{r}
mobeast_loop <- mobeast_delta %>% select(variable) %>% distinct() %>% pull()

models_delta <- vector(mode = "list", length = length(mobeast_loop))
names(models_delta) <- mobeast_loop

for (var in mobeast_loop) {
  df <- mobeast_delta %>% filter(variable == var) %>% as.data.frame()
  
  # you need to have the id numbers as rownames for later when you extract the residuals otherwise residuals will not be associated to a sample. DO NOT DELETE. 
  rownames(df) <- df$id_number
  
  models_delta[[var]] <- lm(conc_norm ~ flowrate , data = df)
}
```


#### model results (fixed/random)
```{r}
# save the outputs of the model in a dataframe (fixed and random effects)
delta_results <- imap_dfr(models_delta, ~ tidy(.x) %>%
                     dplyr::mutate(variable = .y)) %>% 
  relocate(variable, .before = "term")
delta_results
```




```{r}

delta_result_gt <- delta_results %>% left_join(meta_label) %>% 
  relocate(variable_cat) %>% 
  arrange(variable_cat, variable) %>% 
  gt(rowname_col = "variable", groupname_col = "variable_cat") %>% 
  tab_style(
    style = cell_text(weight = "bold", size = "large"),
    locations = cells_row_groups()
  ) %>% 
  cols_hide(variable_cat) %>% 
  tab_style(
  style = cell_text(color = "#2E7D32", weight = "bold"),
  locations = cells_body(
    columns = p.value,
    rows = p.value < 0.05
  )
) %>%
tab_style(
  style = cell_text(color = "grey50"),
  locations = cells_body(
    columns = p.value,
    rows = p.value >= 0.05
  )
) 

#gtsave(delta_result_gt, "delta_result_gt.png", path = here("outputs") )
```



```{r}
# not all stats are saved in the DF
delta_stats <- imap_dfr(models_delta, ~ {
  glance(.x) %>%
    mutate(variable = .y)
}) %>%
  relocate(variable) %>% 
  select(variable, r.squared, adj.r.squared, 
         RSE = sigma, F_stat = statistic, p.value,  DF = df.residual)

delta_stats_gt <- delta_stats %>% left_join(meta_label) %>% 
  relocate(variable_cat) %>% 
  arrange(variable_cat, variable) %>% 
  gt(rowname_col = "variable", groupname_col = "variable_cat") %>% 
  tab_style(
    style = cell_text(weight = "bold", size = "large"),
    locations = cells_row_groups()
  ) %>% 
  cols_hide(variable_cat) %>% 
  tab_style(
  style = cell_text(weight = "bold", color = "blue"),
  locations = cells_body(
    columns = r.squared,
    rows = r.squared == max(r.squared, na.rm = TRUE)
  )
) %>%
tab_style(
  style = cell_text(weight = "bold", color = "red"),
  locations = cells_body(
    columns = r.squared,
    rows = r.squared == min(r.squared, na.rm = TRUE)
  )
) %>% 
  tab_style(
  style = cell_text(weight = "bold", color = "blue"),
  locations = cells_body(
    columns = F_stat,
    rows = F_stat == max(F_stat, na.rm = TRUE)
  )
) %>%
tab_style(
  style = cell_text(weight = "bold", color = "red"),
  locations = cells_body(
    columns = F_stat,
    rows = F_stat == min(F_stat, na.rm = TRUE)
  )
) %>% 
  tab_style(
  style = cell_text(weight = "bold", color = "red"),
  locations = cells_body(
    columns = RSE,
    rows = RSE == max(RSE, na.rm = TRUE)
  )
) %>%
tab_style(
  style = cell_text(weight = "bold", color = "blue"),
  locations = cells_body(
    columns = RSE,
    rows = RSE == min(RSE, na.rm = TRUE)
  )
)
  

#gtsave(delta_stats_gt, "delta_stats_gt.png", path = here("outputs"))

```

## graphing 

```{r, warning = FALSE, fig.height=12, fig.width=20}
mobeast_delta %>% 
  filter(variable_cat == "nutrients") %>% 
  #filter(variable =="pro"|variable =="syn"|variable =="pico_euk"|variable =="het_bact") %>% 
  ggplot(aes(x = flowrate, y = conc_norm, color = treatment)) +
  geom_point(size = 2, alpha = 0.8) +
  geom_point(shape = 21,color = "black", size = 2)+
  geom_smooth(method = "lm", se = TRUE, color = "red") +
  facet_wrap(~ variable, scales = "free_y", nrow= 3, ncol = 3) +
  theme_bw() +
  labs(
    x = "Flow rate",
    y = "Delta Value",
    title = "Flow rate vs Delta for each variable"
  )+
  scale_color_manual(
        breaks = c("Control", "Coral", "CCA", "Algae"),
        values = c("grey", "#03A9F4", "#EF5350", "#4CAF50")
      ) +
  nunu_theme
```

```{r}
mobeast_delta %>% 
  #filter(variable == "npoc_u_m") %>% 
  ggplot(aes(sample = (conc_norm))) +
  #ggplot(aes(sample = sign(conc_norm) * log1p(abs(conc_norm)))) +
  stat_qq() +
  stat_qq_line( color = "red") +
  facet_wrap(.~ variable, scales = "free")

```



```{r, fig.height=100, fig.width=7}
mobeast_delta %>% 
  ggplot( aes(x = flowrate, y = conc_norm)) +
  geom_point(size = 2, alpha = 0.8) +
  geom_smooth(method = "lm", se = TRUE, color = "blue") +
  
  facet_nested(
    variable_cat + variable~. ,
    scales = "free_y"
  ) +
  
  theme_bw(base_size = 14) +
  labs(
    x = "log10 (Flow rate)",
    y = "Delta values",
    title = "Flow rate vs Delta values grouped by category"
  )
```



```{r}
mobeast_delta %>%  
  filter(variable == "het_bact") %>% 
  ggplot(aes(x= treatment, y= conc_norm, fill = treatment))+
    geom_violin()+
    geom_point()+
    geom_hline(yintercept=0, linetype='dashed')+
    stat_summary(color = "yellow", alpha =0.5)+
    #coord_trans(y="log10")+
  facet_wrap(~time_string)+
    labs(title = paste("24h concentrations"),
       x= "Treatment",
       y = "Concentration (µmol/L)")+
  scale_fill_manual(breaks = c("Control", "Coral", "CCA", "Algae"), 
                       values=c("grey", "#03A9F4", "#EF5350", "#4CAF50"))+
  nunu_theme +
  theme(legend.position = "none")
```



## extracting the residuals

```{r}
# create a list of variable that I want to extract the residuals on 
mobeast_loop <- mobeast_delta %>% select(variable) %>% distinct() %>% pull()

# create empty dataframe to store the reisduals
mobeast_resid <- data.frame()


for (var in mobeast_loop) {
  
  # preparing the df in which i want to add the residuals
  meta <- mobeast_delta %>% filter(variable == var)
  
  # extract the residuals from the models and join them to the original dataframe
  df <- augment(models_delta[[var]]) %>% 
    select(id_number = .rownames, resid = .resid) %>% right_join(meta)
  
  #binding the data by variable to one single dataframe
  mobeast_resid <- rbind(mobeast_resid, df)

}


```


##graphing the residual distribution 


```{r}
# cleaning the df so that i have ordered treatment and time
mobeast_resid<- mobeast_resid %>% 
  mutate(treatment = factor(treatment, 
                            levels = c("Control", "Coral", 
                                       "CCA", "Algae")),
         time_fac = factor(as.character(time_string), 
                           levels = c("12:00:00", "18:00:00",
                                      "00:00:00", "06:00:00"))
         )
```

```{r}
# iterative graphing over all the vriables of interest

resid_loop <- mobeast_resid %>% select(variable) %>% distinct() %>% pull()

graphs_resid <- vector(mode = "list", length = length(resid_loop))
names(graphs_resid) <- resid_loop

for (var in resid_loop) {
  
  df <- mobeast_resid %>% filter(variable == var)
  
  graph_1 <- df %>%
  ggplot(aes(x = treatment, y = resid, fill = treatment)) +
      geom_violin() +
      geom_point() +
      geom_hline(yintercept = 0, linetype = "dashed") +
      stat_summary(color = "yellow", alpha = 0.5) +
      labs(title = paste("24h residuals"),
           x = "Treatment",
          y = "Residuals ") +
      scale_fill_manual(
        breaks = c("Control", "Coral", "CCA", "Algae"),
        values = c("grey", "#03A9F4", "#EF5350", "#4CAF50")
      ) +
      nunu_theme +
      theme(legend.position = "none")
  
  graph_2 <- df %>%
  ggplot(aes(x = treatment, y = resid, fill = treatment)) +
      geom_violin() +
      geom_point() +
      geom_hline(yintercept = 0, linetype = "dashed") +
      stat_summary(color = "yellow", alpha = 0.5) +
    facet_wrap(.~time_fac, ncol = 4)+
      labs(title = paste("24h residuals by time "),
           x = "Treatment",
          y = "Residuals ") +
      scale_fill_manual(
        breaks = c("Control", "Coral", "CCA", "Algae"),
        values = c("grey", "#03A9F4", "#EF5350", "#4CAF50")
      ) +
      nunu_theme +
      theme(legend.position = "none")
  
  graphs_resid[[var]] <- graph_1/graph_2
}


```


```{r}
graphs_resid[["het_bact"]]
```

```{r}
## DOC has weird 00:00 values and should be omitted from the graphs  (maybe?)
graph_1 <- mobeast_resid %>% filter(variable == "npoc_u_m") %>% 
  filter(time_fac != "00:00:00") %>% 
  ggplot(aes(x = treatment, y = resid, fill = treatment)) +
      geom_violin() +
      geom_point() +
      geom_hline(yintercept = 0, linetype = "dashed") +
      stat_summary(color = "yellow", alpha = 0.5) +
      labs(title = paste("24h residuals"),
           x = "Treatment",
          y = "Residuals ") +
      scale_fill_manual(
        breaks = c("Control", "Coral", "CCA", "Algae"),
        values = c("grey", "#03A9F4", "#EF5350", "#4CAF50")
      ) +
      nunu_theme +
      theme(legend.position = "none")
  
graph_2 <- mobeast_resid %>% filter(variable == "npoc_u_m") %>% 
  filter(time_fac != "00:00:00") %>% 
  ggplot(aes(x = treatment, y = resid, fill = treatment)) +
      geom_violin() +
      geom_point() +
      geom_hline(yintercept = 0, linetype = "dashed") +
      stat_summary(color = "yellow", alpha = 0.5) +
    facet_wrap(.~time_fac, ncol = 4)+
      labs(title = paste("24h residuals by time "),
           x = "Treatment",
          y = "Residuals ") +
      scale_fill_manual(
        breaks = c("Control", "Coral", "CCA", "Algae"),
        values = c("grey", "#03A9F4", "#EF5350", "#4CAF50")
      ) +
      nunu_theme +
      theme(legend.position = "none")
  
 graph_1/graph_2
```



# Lmer models  - Iterative  coding 

```{r}
# Loop Function:
## Take the 12PM samples and isolate the types of nutrient present on the df in a vector
## Create a list where the loop results will be save, named after the nutrients of the df
## In the for-loop, filter the df by nutrient and apply a statistical model with lmer
## Save the outputs of the model in the list such that each nutrient has its stats

resid_loop <- mobeast_resid %>% select(variable) %>% distinct() %>% pull()

models_resid_lmer <- vector(mode = "list", length = length(resid_loop))
names(models_resid_lmer) <- resid_loop

for (var in resid_loop) {
  df <- mobeast_resid %>% filter(variable == var)
  models_resid_lmer[[var]] <- lmer(resid ~ treatment + (1|tank_number), data = df)

}

```


#### model results 
```{r}
# save the outputs of the model in a dataframe (fixed and random effects)
results_resid <- imap_dfr(models_resid_lmer, ~ tidy(.x) %>%
                     dplyr::mutate(variable = .y)) %>% 
  relocate(variable, .before = "effect")
results_resid
```


#### ANOVA results 
```{r, warning= FALSE}
# So many Warnings! 
## Warning: The column names NumDF and DenDF in ANOVA output were not recognized or transformed.

# run anova on the models 
anova_results <- imap_dfr(models_12PM_2, ~ {
  stats::anova(.x, type = 2) %>%
    broom::tidy() %>%
    mutate(variable = .y)}) %>%
  relocate(variable) 

## which variables have significant anova results
anova_results %>% filter(p.value <0.05)
# tot-bact, syn, fpeak and npoc are significant. 
```


#### Emmeans results 
```{r}
# "estimate" are negative somehow. Why? 
## in manual models for DOC, estimate >0, here it's <0
## t.ratio in "statistics", and negative instead of positive
## p.values not shown, only p.adjusted. 
emmeans_results <- imap_dfr(models_12PM_2, ~ {
  emmeans(.x, pairwise ~ treatment)$contrasts %>%
    broom::tidy() %>%
    mutate(variable = .y)}) %>% 
  relocate(variable) %>% 
  filter(contrast == "Control - Coral"| contrast == "Control - CCA"|contrast == "Control - Algae") 


emmeans_results_sig <- emmeans_results %>% 
  filter(adj.p.value <0.05)

emmeans_results
emmeans_results_sig # there are no significant variables....
```


