---
author: 'Keanu Rochette '
date: '`r format(Sys.Date())`'
title: DIC Prelim data
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE , 
                      warning = FALSE)
```

## Load Libraries 
```{r}
library(tidyverse)
library(here)
library(janitor)
library(ggrepel)
library(ghibli)
library(gt)
library(car) # ANOVA package
library(ggeffects)
library(effects) #dependency for ggeffects
library(ggResidpanel) #residual panel
library(GGally)
library(emmeans)

library(seacarb)
library(broom)
library(ggridges)
library(moments)
library(agricolae)
```

## Load function
```{r}
source(here("functions", "function_ANOVA_nunu.R"))
```

## Data visualization theme
```{r}

nunu_theme <- theme_bw() + 
  theme(plot.title = element_text(size=14, face = "bold"), 
        plot.subtitle = element_text(size=12),
        axis.title = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 12),
        strip.text.x = element_text(size = 12, face = "bold"),
        legend.title=element_text(size=12, face = "bold"),
        legend.text=element_text(size=12),
        axis.text.x = element_text(angle= 45, hjust= 1),
        panel.background = element_rect(fill = "azure1"))
```

## Load Data
```{r}
pHcalib<-read_csv(here("Data","Laurel", "TrisCalSummer2024.csv"))
pHData<-read_csv(here("Data", "Laurel", "24_hr_carb_chem.csv"))
TableID<-read_csv(here("Data","Laurel", "TableID.csv"))
```

```{r}
TableID<-TableID %>% select(TankID = TANKID, 
                   InflowTable = INFLOW_TABLE, 
                   Treatment = TREATMENT)
```

## calculate pH slope using mV 
```{r}

pHSlope<-pHcalib %>%
  nest_by(TrisCalDate)%>%
  mutate(fitpH = list(lm(mVTris~TTris, data = data))) %>% # linear regression of mV and temp of the tris
  summarise(broom::tidy(fitpH)) %>% # make the output tidy
  select(TrisCalDate, term, estimate) %>%
  pivot_wider(names_from = term, values_from = estimate) %>%# put slope and intercept in their own column
  right_join(.,pHData) %>% # join with the pH sample data
  mutate(mVTris = TempInLab*TTris + `(Intercept)`) %>% # calculate the mV of the tris at temperature in which the pH of samples were measured
  drop_na(TempInSitu)%>%
  drop_na(mV) %>%
  mutate(pH = pH(Ex=mV,Etris=mVTris,S=Salinity,T=TempInLab))  # calculate pH of the samples using the pH seacarb function

```

## calculate pH insitu
```{r}
 
pHSlope <- pHSlope%>%
  mutate(pH_insitu = pHinsi(pH = pH, ALK = 2200, Tinsi = TempInSitu, Tlab = TempInLab, 
                            S = Salinity,Pt = 0.1, k1k2 = "m10", kf = "dg")) %>%
  select(!pH)%>%
  rename(pH = pH_insitu) %>% # rename it 
  ungroup() %>% 
  mutate(Date = ymd(Date))
  #select(-c(TempInLab, mV, TrisCalDate, TTris, `(Intercept)`, mVTris))
```


## calculate inflow data using pH slope and flow by each inflow table ##
```{r}
InflowData <- pHSlope %>%
  filter(TankID %in% c("Inflow1","Inflow2")) %>%
  select(-c(Flow_Left_30s, Flow_Right_30s, Notes, DO_mg_L, Salinity, TempInSitu))  %>% ### remove the values that I don't need -- You will eventually need to keep TA which is why I dropped these instead of coding for the ones that I need
  rename(pH_inflow = pH,
         TA_inflow = TA) %>%# rename the pH to show that it is inflow pH
  mutate(InflowTable = ifelse(TankID == "Inflow1",1,2)) %>% # give them inflow numbers to pair easily with the TankID 
  ungroup()%>%
  select(Date,Time,InflowTable, pH_inflow, TA_inflow) # drop the Tank ID column to be able to join the data correctly by inflow #
```

```{r}
SurfaceArea <- 22.5*22.5 # put in the surface area in cm2 for the bottom of the tank here
```

```{r}
## join inflow data, table ID. calculate residence time, delta TA, and NEC ##
Data <- pHSlope %>%
  ungroup()%>%
  filter(!TankID %in% c("Inflow1","Inflow2"))%>% # filter out the inflow data now
  mutate(TankID = as.numeric(TankID))%>% # convert to numeric since the inflow data is now dropped
  left_join(TableID, by = "TankID") %>%
  left_join(InflowData) %>% # join with the inflow data for easier calculations of rates
  mutate(DateTime = ymd_hms(paste(Date, Time)), # make a datetime
         pHDiff = pH - pH_inflow, # calculate the difference between the inflow and the pH in each tank 
         totalflow = Flow_Right_30s+Flow_Left_30s,
         residence_time = (1/totalflow)*(10000/60),# convert ml/min to hours by multiplying by the volumne of water in ml and divide by 60
         deltaTA = TA_inflow - TA, # calculate the difference between in and outflow
         NEC = (deltaTA/2)*(1.025)*(10)*(1/residence_time)*(1/SurfaceArea) ### for a real rate should probably normalize the delta TA to the delta control just like in respo
  )
```

## Codes of the treatment  
```{r}
treat_code <- tibble(
  Treatment = c("Algae_Dom", "Coral_Dom", "Control", "Rubble_Dom"),
  full_name = c("Algae", "Coral", "Control", "CCA")
)
treat_code

```

```{r}
carbonate <- left_join(Data, treat_code, by= "Treatment")

carbonate<- carbonate %>% select(-Treatment) %>% rename(treatment=full_name) %>% clean_names()

carbonate<- carbonate %>% select(tank_id, inflow_table, date, time, 
                     date_time, treatment,
                     ph=p_h, ph_inflow=p_h_inflow, ph_diff =p_h_diff,
                     ta, delta_ta) %>% 
   mutate(treatment = factor(treatment, # reorder the factor treatments 
                            levels = c("Control","Coral",
                                       "CCA", "Algae"))) 
```


## Data visualization
## pH difference
```{r, height=12, width = 8}
carbonate %>% 
  group_by(date_time, treatment) %>%
  summarise(avg = mean(ph_diff, na.rm = T),
            n = n(),
            se = sd(ph_diff, na.rm = T)/sqrt(n))%>% 
  ungroup() %>% 
  ggplot(aes(x=date_time, y= avg , color = treatment))+
  geom_point(size = 2)+
  geom_line(linewidth = 1)+
  geom_hline(yintercept=0, linetype="dashed", color = "orange", alpha =0.8)+
  geom_pointrange(aes(ymin= avg-se, ymax= avg+se)) +
  facet_grid(treatment ~.)+
  labs(title= "24h pH difference variations",
       x= "Date Time",
       y= "pH difference",
       caption= "Credit: Laurel Diaz, Nyssa Silbiger, Ph.D.")+
  scale_color_manual(breaks = c("Control", "Coral", "CCA", "Algae"), 
                       values=c("grey", "#03A9F4", "#EF5350", "#4CAF50"))+
  nunu_theme +
  theme(legend.position = "none",
        axis.text.x = element_text(angle= 0, hjust= 0.5))

ggsave(filename = "pH_diff_24h.png",plot = last_plot(), path = here("outputs"), width = 8, height = 12)
```

```{r}
ph_lm <- lm(ph ~ treatment, data = carbonate)

emmeans(ph_lm,specs = trt.vs.ctrl ~ treatment)
```



```{r, height=12, width = 8}
carbonate %>% drop_na() %>% 
  group_by(date_time, treatment) %>%
  summarise(avg = mean(delta_ta, na.rm = T),
            n = n(),
            se = sd(delta_ta, na.rm = T)/sqrt(n))%>% 
  ungroup() %>% 
  ggplot(aes(x=date_time, y= avg , color = treatment))+
  geom_point(size = 2)+
  geom_line(linewidth = 1)+
  geom_hline(yintercept=0, linetype="dashed", color = "orange", alpha =0.8)+
  geom_pointrange(aes(ymin= avg-se, ymax= avg+se)) +
  facet_grid(treatment ~.)+
  labs(title= "24h delta alkalinity variations",
       x= "Date Time",
       y= "Delta TA",
       caption= "Credit: Laurel Diaz, Nyssa Silbiger, Ph.D.")+
  scale_color_manual(breaks = c("Control", "Coral", "CCA", "Algae"), 
                       values=c("grey", "#03A9F4", "#EF5350", "#4CAF50"))+
  nunu_theme +
  theme(legend.position = "none",
        axis.text.x = element_text(angle= 0, hjust= 0.5))

#ggsave(filename = "delta_ta_24h.png",plot = last_plot(), path = here("outputs"), width = 8, height = 12)
```

```{r, height=12, width = 8}
carbonate %>% drop_na() %>% 
  ggplot(aes(x=date_time, y= delta_ta , color = treatment, group = tank_id))+
  geom_point(size = 2)+
  geom_line(linewidth = 1)+
  #geom_hline(yintercept=0, linetype="dashed", color = "orange", alpha =0.8)+
  #geom_pointrange(aes(ymin= avg-se, ymax= avg+se)) +
  facet_grid(treatment ~.)+
  labs(title= "24h delta alkalinity variations",
       x= "Date Time",
       y= "Delta TA",
       caption= "Credit: Laurel Diaz, Nyssa Silbiger, Ph.D.")+
  scale_color_manual(breaks = c("Control", "Coral", "CCA", "Algae"), 
                       values=c("grey", "#03A9F4", "#EF5350", "#4CAF50"))+
  nunu_theme +
  theme(legend.position = "none",
        axis.text.x = element_text(angle= 0, hjust= 0.5))

#ggsave(filename = "delta_ta_24h.png",plot = last_plot(), path = here("outputs"), width = 8, height = 12)
```






